// Isolated HTTP coverage for commercial bootstrap, proxy, permissions and credential revocation.
import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {resolve} from 'node:path';import {randomUUID} from 'node:crypto';
const root=resolve('test-results','commercial-http-'+randomUUID()),base='http://127.0.0.1:5057';await mkdir(root,{recursive:true});
const server=spawn('dotnet',[resolve('bin/Debug/net10.0/CfcPilot.dll'),'--urls',base],{cwd:resolve('.'),env:{...process.env,CFC_DATA_DIR:root,CFC_INSTALLATION_MODE:'commercial',CFC_SCHOOL_ID:'http-test',CFC_SCHOOL_NAME:'Autoescola sintética',CFC_TRUSTED_PROXY:'127.0.0.1',NativePortal__Enabled:'false'},windowsHide:true,stdio:['ignore','pipe','pipe']});let output='';server.stdout.on('data',b=>output+=b);server.stderr.on('data',b=>output+=b);let passed=0;
const check=(v,n)=>{assert(v,n);passed++;console.log('PASS '+n);};
function client(){let cookie='';const call=async(path,body,{secure=true,origin='',key='',cookieOverride='',method=''}={})=>{const r=await fetch(base+'/api/'+path,{method:method||(body===undefined?'GET':'POST'),headers:{...(secure?{'X-Forwarded-Proto':'https'}:{}),...(cookieOverride||cookie?{Cookie:cookieOverride||cookie}:{}),...(origin?{Origin:origin}:{}),...(body===undefined?{}:{'Content-Type':'application/json','X-CFC-Client':'pilot'}),...(key?{'X-Operation-Id':key}:{})},body:body===undefined?undefined:JSON.stringify(body)});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return{status:r.status,body:await r.json().catch(()=>({})),headers:r.headers,cookie};};return{call,getCookie:()=>cookie};}
try{for(let i=0;i<100;i++){try{if((await fetch(base+'/api/health')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
for(const [route,title] of [['/install/','Receba seu acesso'],['/account/','Seu acesso pessoal'],['/portal/','CFC+']]){const page=await fetch(base+route);check(page.ok&&(await page.text()).includes(title),'Página publicada '+route);}
const admin=client(),other=client();check((await admin.call('distribution',undefined,{secure:false})).status===400,'API comercial exige HTTPS');check((await admin.call('auth/me')).status===401,'Conta pessoal exige autenticação');check((await admin.call('distribution')).body.schoolName==='Autoescola sintética','Identidade pública não contém segredos');
const initial=JSON.parse(await readFile(resolve(root,'first-access.json'),'utf8'));const auth=await admin.call('auth/login',initial);check(auth.status===200&&auth.body.mustChangePassword,'Primeiro acesso exige trocar senha');check(/secure/i.test(auth.headers.get('set-cookie')),'Cookie comercial é Secure');check((await admin.call('snapshot')).status===428,'Senha inicial não libera operações');
const password='new-'+randomUUID();const changed=await admin.call('auth/password',{currentPassword:initial.password,newPassword:password},{key:randomUUID()});check(changed.status===200,'Titular altera a própria senha');check((await admin.call('auth/login',{login:'admin',password:initial.password})).status===401,'Senha inicial deixa de funcionar');check((await admin.call('auth/login',{login:'admin',password})).status===200,'Senha nova autentica');const oldCookie=admin.getCookie();check((await admin.call('snapshot')).body.students.length===0,'Base comercial começa sem alunos fictícios');
check((await admin.call('system/imports')).body.empty,'Importação identifica base vazia');check((await admin.call('commands/user',{name:'Atendente teste',login:'clerk',role:'Atendente',password:'clerk-test-password',active:true},{key:randomUUID()})).status===200,'Administrador cria acesso da equipe');check((await other.call('auth/login',{login:'clerk',password:'clerk-test-password'})).body.mustChangePassword,'Acesso criado exige nova senha pessoal');await other.call('auth/password',{currentPassword:'clerk-test-password',newPassword:'changed-clerk-password'},{key:randomUUID()});await other.call('auth/login',{login:'clerk',password:'changed-clerk-password'});check((await other.call('system/imports')).status===403,'Atendente não lê importações');
check((await admin.call('system/imports',{}, {origin:'https://malicious.example'})).status===403,'Origem externa não cria importação');
const times=[];await Promise.all(Array.from({length:30},async()=>{const start=performance.now();const r=await admin.call('snapshot');assert.equal(r.status,200);times.push(performance.now()-start);}));times.sort((a,b)=>a-b);check(times.length===30,'30 consultas concorrentes concluídas');
const upload=await admin.call('system/imports',{name:'invalid.zip',bytes:4});const j=upload.body;const chunk=await fetch(base+'/api/system/imports/'+j.id+'/chunk?offset=0',{method:'POST',headers:{'X-Forwarded-Proto':'https','X-CFC-Client':'pilot',Cookie:admin.getCookie()},body:Buffer.from('bad!')});check(chunk.status===200,'Upload binário utiliza trechos autenticados');await admin.call('system/imports/'+j.id+'/verify',{});let job;for(let n=0;n<100;n++){await new Promise(r=>setTimeout(r,100));job=(await admin.call('system/imports')).body.jobs[0];if(job.state==='Falhou')break;}check(job.state==='Falhou','ZIP inválido vira falha isolada no job');check((await fetch(base+'/api/health')).status===200,'Falha de importação não derruba o atendimento');
const newPass='next-'+randomUUID();await admin.call('auth/password',{currentPassword:password,newPassword:newPass},{key:randomUUID()});check((await other.call('auth/me',undefined,{cookieOverride:oldCookie})).status===401,'Troca de senha revoga sessões antigas');
await writeFile(resolve(root,'result.json'),JSON.stringify({ok:true,checks:passed,load:{requests:30,concurrency:30,dataset:'empty synthetic school',p50Ms:times[15],p95Ms:times[28],maxMs:times.at(-1)},realData:false},null,2));console.log(passed+' verificações HTTP comerciais aprovadas.');console.log('p95 base vazia: '+Math.round(times[28])+' ms');
}catch(e){await writeFile(resolve(root,'server-test.log'),output);throw e;}finally{server.kill();}
