using System.Text;
using System.Text.Json;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.Extensions.FileProviders;
namespace CfcPilot;
public static class CommunityChecks
{
    sealed class Env(string root):IWebHostEnvironment
    {public string ApplicationName{get;set;}="CfcPilot";public string EnvironmentName{get;set;}="Testing";public string ContentRootPath{get;set;}=root;public IFileProvider ContentRootFileProvider{get;set;}=new NullFileProvider();public string WebRootPath{get;set;}=root;public IFileProvider WebRootFileProvider{get;set;}=new NullFileProvider();}
    public static void Run()=>RunAsync().GetAwaiter().GetResult();
    static async Task RunAsync()
    {
        var passed=0;void Check(bool yes,string label){if(!yes)throw new InvalidOperationException(label);passed++;Console.WriteLine("PASS "+label);}
        async Task Reject(Func<Task> action,int code,string label){try{await action();throw new InvalidOperationException(label);}catch(RuleException ex){Check(ex.Status==code,label);}}
        JsonElement Body(object value)=>JsonSerializer.SerializeToElement(value,Database.Compact);JsonElement Json(object value)=>Body(value);JsonElement Result(string value)=>JsonDocument.Parse(value).RootElement.Clone();
        var root=Path.GetFullPath(Path.Combine("test-results","community-"+Guid.NewGuid().ToString("N")));Directory.CreateDirectory(root);
        User admin=new User{Id="a",Name="Admin",Role="Administrador"},student=new User{Id="us1",Role="Aluno",LinkedId="s1"},otherStudent=new User{Id="us2",Role="Aluno",LinkedId="s2"},instructor=new User{Id="ui1",Role="Instrutor",LinkedId="i1"},clerk=new User{Id="clerk",Role="Atendente",UnitId="u2"};
        string past=Operations.Now.AddDays(-1).ToString("s"),future=Operations.Now.AddDays(2).ToString("s");
        var state=new State{Units=[new(){Id="u1",Name="Escola teste"},new(){Id="u2",Name="Outra escola"}],Students=[new(){Id="s1",Name="Aluno teste",UnitId="u1",Cpf="CPF_PRIVADO_1",Notes="NOTA_INTERNA"},new(){Id="s2",Name="Outro aluno",UnitId="u2",Cpf="CPF_PRIVADO_2"}],Instructors=[new(){Id="i1",Name="Instrutor teste",UnitId="u1",Cpf="CPF_INSTRUTOR"},new(){Id="i2",Name="Outro instrutor",UnitId="u2"}],Enrollments=[new(){Id="e1",StudentId="s1",UnitId="u1",Category="B",LessonLimit=4}],Documents=[new(){Id="d1",StudentId="s1",Name="Contrato teste",Text="MEU DOCUMENTO"},new(){Id="d2",StudentId="s2",Name="Documento alheio",Text="SEGREDO ALHEIO"}],Entries=[new(){Id="p1",StudentId="s1",EnrollmentId="e1",Kind="Débito",Amount=100},new(){Id="p2",StudentId="s2",Kind="Débito",Amount=9999}],Lessons=[new(){Id="l1",StudentId="s1",EnrollmentId="e1",InstructorId="i1",UnitId="u1",Start=past,Status="Realizada"},new(){Id="l2",StudentId="s2",InstructorId="i2",UnitId="u2",Start=past,Status="Realizada"},new(){Id="l3",StudentId="s1",InstructorId="i1",UnitId="u1",Start=future},new(){Id="l4",StudentId="s2",InstructorId="i2",UnitId="u2",Start=future},new(){Id="l5",StudentId="s1",InstructorId="i1",UnitId="u1",Start=past},new(){Id="l6",StudentId="s1",InstructorId="i1",UnitId="u1",Start=future},new(){Id="excluded",StudentId="s1",InstructorId="i1",Start=past,ExcludedFromAgenda=true}]};
        File.WriteAllText(Path.Combine(root,"pilot.json"),JsonSerializer.Serialize(state,Store.Json));var config=new ConfigurationBuilder().AddInMemoryCollection(new Dictionary<string,string?>{["CFC_DATA_DIR"]=root}).Build();var env=new Env(root);var store=new Store(config,env);var resources=new StudentResources(store,config,env,DataProtectionProvider.Create(new DirectoryInfo(Path.Combine(root,"keys"))));var svc=new CommunityPortal(store,config,env,resources);
        var snapshot=Json(await svc.Snapshot(student));var raw=snapshot.GetRawText();Check(!raw.Contains("CPF_PRIVADO")&&!raw.Contains("NOTA_INTERNA")&&!raw.Contains("SEGREDO ALHEIO"),"Portal não expõe documentos, identificadores ou notas de terceiros");Check(snapshot.GetProperty("lessons").GetArrayLength()==4,"Aluno só vê próprias aulas sem duplicata excluída");Check(snapshot.GetProperty("finance").GetProperty("balance").GetDecimal()==100,"Financeiro isolado ao titular");Check(Json(await svc.Snapshot(instructor)).GetProperty("lessons").GetArrayLength()==4,"Instrutor só vê suas aulas");
        await Reject(async()=>{await svc.Snapshot(student,"Aluno","s2");},403,"Titular não troca o vínculo por parâmetros");await Reject(async()=>{await svc.Snapshot(new User{Role="Aluno"});},409,"Acesso sem ficha vinculada é recusado");Check(Json(await svc.Snapshot(admin,"Aluno","s1")).GetProperty("preview").GetBoolean(),"Equipe tem visualização explicitamente somente leitura");await Reject(async()=>{await svc.Snapshot(clerk,"Aluno","s1");},403,"Visualização respeita a unidade do atendimento");
        var request=Body(new{type="Remarcar aula",message="Preciso de outro horário",lessonId="l3",owner="s2"});var op=Guid.NewGuid().ToString();var first=await svc.Request(student,request,op);Check(first==await svc.Request(student,request,op),"Reenvio não duplica solicitação");Check(Result(first).GetProperty("owner").GetString()=="s1","Titular da solicitação é decidido pelo servidor");await Reject(async()=>{await svc.Request(student,Body(new{type="Remarcar aula",message="Outra mensagem",lessonId="l3"}),op);},409,"Identificador não pode ser reutilizado em outro conteúdo");await Reject(async()=>{await svc.Request(student,Body(new{type="Remarcar aula",message="Mensagem válida",lessonId="l4"}),Guid.NewGuid().ToString());},403,"Aluno não solicita alteração de aula alheia");await Reject(()=>Task.Run(()=>svc.Inbox(student)),403,"Aluno não acessa fila da escola");
        var item=Result(first);await Reject(()=>Task.Run(()=>svc.Reply(student,item.GetProperty("id").GetString()!,Body(new{reply="resposta",status="Concluída",version=item.GetProperty("version").GetString()}),Guid.NewGuid().ToString())),403,"Aluno não responde como atendimento");await Reject(()=>Task.Run(()=>svc.Reply(clerk,item.GetProperty("id").GetString()!,Body(new{reply="resposta",status="Concluída",version=item.GetProperty("version").GetString()}),Guid.NewGuid().ToString())),403,"Atendente não responde outra unidade");var replyBody=Body(new{reply="Vamos combinar o novo horário",status="Em atendimento",version=item.GetProperty("version").GetString()});var replyOp=Guid.NewGuid().ToString();var reply=svc.Reply(admin,item.GetProperty("id").GetString()!,replyBody,replyOp);Check(reply==svc.Reply(admin,item.GetProperty("id").GetString()!,replyBody,replyOp),"Reenvio de resposta é idempotente");await Reject(()=>Task.Run(()=>svc.Reply(admin,item.GetProperty("id").GetString()!,replyBody,Guid.NewGuid().ToString())),409,"Resposta não sobrescreve atualização concorrente");Check(Json(await svc.Snapshot(student)).GetProperty("requests")[0].GetProperty("reply").GetString()=="Vamos combinar o novo horário","Aluno recebe a resposta da escola");Check(Json(await svc.Snapshot(otherStudent)).GetProperty("requests").GetArrayLength()==0,"Solicitações de outro aluno são isoladas");
        var confirm=Body(new{type="Confirmar presença",lessonId="l3"});var c1=await svc.Request(student,confirm,Guid.NewGuid().ToString());var c2=await svc.Request(student,confirm,Guid.NewGuid().ToString());Check(Result(c1).GetProperty("id").GetString()==Result(c2).GetProperty("id").GetString(),"Confirmação repetida gera um único registro");Check((await store.Read()).Lessons.Single(x=>x.Id=="l3").Status=="Agendada","Confirmar intenção não realiza nem valida aula");
        var skills=CommunityPortal.SkillNames.ToDictionary(x=>x,x=>3);var assessment=Body(new{skills,publicNote="Continue praticando as manobras",privateNote="NOTA_PRIVADA_INSTRUTOR",version=""});await svc.Assess(instructor,"l1",assessment,Guid.NewGuid().ToString());Check(!Json(await svc.Snapshot(student)).GetRawText().Contains("NOTA_PRIVADA_INSTRUTOR"),"Observação privada não chega ao aluno");Check(Json(await svc.Snapshot(student)).GetRawText().Contains("Continue praticando"),"Orientação pública aparece para o aluno");Check(Json(await svc.Snapshot(instructor)).GetRawText().Contains("NOTA_PRIVADA_INSTRUTOR"),"Instrutor pode rever sua observação privada");await Reject(async()=>{await svc.Assess(instructor,"l2",assessment,Guid.NewGuid().ToString());},403,"Avaliação de outro instrutor recusada");await Reject(async()=>{await svc.Assess(student,"l1",assessment,Guid.NewGuid().ToString());},403,"Aluno não se autoavalia como instrutor");await Reject(async()=>{await svc.Assess(instructor,"l3",assessment,Guid.NewGuid().ToString());},409,"Avaliação exige aula realizada");await Reject(async()=>{await svc.Assess(instructor,"l1",assessment,Guid.NewGuid().ToString());},409,"Avaliação antiga não sobrescreve versão nova");
        await svc.Attendance(instructor,"l5",Body(new{status="Realizada"}),Guid.NewGuid().ToString());var attendance=(await store.Read()).Lessons.Single(x=>x.Id=="l5");Check(attendance.Status=="Realizada"&&!attendance.Validated,"Realização interna não cria validação DETRAN");await Reject(async()=>{await svc.Attendance(instructor,"l4",Body(new{status="Falta"}),Guid.NewGuid().ToString());},403,"Presença de aula alheia recusada");await Reject(async()=>{await svc.Attendance(instructor,"l6",Body(new{status="Realizada"}),Guid.NewGuid().ToString());},400,"Aula futura não pode ser realizada");
        var bytes=Encoding.ASCII.GetBytes("%PDF-1.4\nARQUIVO FICTICIO\n%%EOF");var file=new FormFile(new MemoryStream(bytes),0,bytes.Length,"file","teste.pdf");var fileOp=Guid.NewGuid().ToString();var attachment=await svc.Upload(student,file,"Documento teste","Outro",fileOp);Check(attachment.StudentId=="s1","Arquivo enviado fica na própria ficha");Check((await svc.Upload(student,file,"Documento teste","Outro",fileOp)).Id==attachment.Id,"Reenvio de documento não duplica arquivo");Check((await resources.Read(student,attachment.Id)).Bytes.SequenceEqual(bytes),"Aluno pode baixar seu documento protegido");await Reject(async()=>{await resources.Read(otherStudent,attachment.Id);},403,"Outro aluno não baixa o documento");Check((await svc.Document(student,"d1")).Text=="MEU DOCUMENTO","Documento gerado disponível ao titular");await Reject(async()=>{await svc.Document(student,"d2");},404,"Documento gerado de terceiro não é acessível");
        await Reject(()=>Task.Run(()=>svc.Configure(student,Body(new CommunityPolicy()))),403,"Titular não altera permissões");svc.Configure(admin,Body(new CommunityPolicy{StudentRequests=false,StudentUploads=false,StudentFinance=false,InstructorAssessment=false,InstructorAttendance=false}));Check(Json(await svc.Snapshot(student)).GetProperty("finance").ValueKind==JsonValueKind.Null,"Administrador pode ocultar financeiro");await Reject(async()=>{await svc.Request(student,request,Guid.NewGuid().ToString());},403,"Política bloqueia novas solicitações");await Reject(async()=>{await svc.Upload(student,file,"Teste","Outro",Guid.NewGuid().ToString());},403,"Política bloqueia novos anexos");await Reject(async()=>{await svc.Assess(instructor,"l1",assessment,Guid.NewGuid().ToString());},403,"Política bloqueia avaliações");await Reject(async()=>{await svc.Attendance(instructor,"l5",Body(new{status="Falta"}),Guid.NewGuid().ToString());},403,"Política bloqueia realização/falta");Check(File.Exists(Path.Combine(root,"community.sqlite")),"Interações persistidas separadamente da importação original");
        var relationalRoot=Path.Combine(root,"relational");Directory.CreateDirectory(relationalRoot);using(var db=Database.Open(Path.Combine(relationalRoot,"fixture.sqlite")))
        {
            Database.Initialize(db);foreach(var property in typeof(State).GetProperties().Where(p=>p.PropertyType.IsGenericType&&p.PropertyType.GetGenericTypeDefinition()==typeof(List<>)))foreach(var entity in (System.Collections.IEnumerable)property.GetValue(state)!)Database.SaveEntity(db,property.Name,entity);
            foreach(var pair in new[]{("searchSchema","2"),("importId","community-fixture"),("policy",JsonSerializer.Serialize(state.Policy,Database.Compact))})Database.Execute(db,"INSERT INTO metadata VALUES($0,$1)",pair.Item1,pair.Item2);
        }
        File.WriteAllText(Path.Combine(relationalRoot,"active-database.json"),"{\"path\":\"fixture.sqlite\"}");var rc=new ConfigurationBuilder().AddInMemoryCollection(new Dictionary<string,string?>{["CFC_DATA_DIR"]=relationalRoot}).Build();var re=new Env(relationalRoot);var rs=new Store(rc,re);var rr=new StudentResources(rs,rc,re,DataProtectionProvider.Create(new DirectoryInfo(Path.Combine(relationalRoot,"keys"))));var relational=new CommunityPortal(rs,rc,re,rr);
        Check(Json(await relational.Snapshot(student)).GetProperty("lessons").GetArrayLength()==4,"Base relacional aplica o mesmo isolamento do aluno");
        Check(Json(await relational.Snapshot(instructor)).GetProperty("students").GetArrayLength()==1,"Base relacional limita alunos ao instrutor");
        Check(!(await rs.Community("Aluno","s1")).Users.Any(),"Consulta do portal não carrega credenciais da equipe");
        Check(Json(await relational.Snapshot(student)).GetProperty("finance").GetProperty("balance").GetDecimal()==100,"Financeiro usa os registros importados da ficha");
        Console.WriteLine($"{passed} verificações dos portais passaram.");
    }
}
