using System.IO.Compression;
using System.Text.Json;
using Microsoft.Extensions.FileProviders;
using Microsoft.Extensions.Logging.Abstractions;
namespace CfcPilot;
public static class CommercialChecks
{
    sealed class Env(string root):IWebHostEnvironment{public string ApplicationName{get;set;}="CfcPilot";public string EnvironmentName{get;set;}="Testing";public string ContentRootPath{get;set;}=root;public IFileProvider ContentRootFileProvider{get;set;}=new NullFileProvider();public string WebRootPath{get;set;}=root;public IFileProvider WebRootFileProvider{get;set;}=new NullFileProvider();}
    public static void CreateFixture(string root){Directory.CreateDirectory(root);var zip=Path.Combine(root,"fixture.zip");using(var schema=JsonDocument.Parse(File.ReadAllText("tests/fixtures/legacy-schema.json")))using(var archive=ZipFile.Open(zip,ZipArchiveMode.Create)){
            var tables=schema.RootElement.GetProperty("tables").EnumerateArray().Select(t=>new{name=t.GetProperty("name").GetString()!,columns=t.GetProperty("columns").EnumerateArray().Select(c=>c.GetString()!).ToArray()}).ToArray();
            foreach(var t in tables){using(var writer=new StreamWriter(archive.CreateEntry("01_BANCO_DE_DADOS_COMPLETO/schema/"+t.name+".sql").Open()))writer.Write("INSERT INTO [dbo].["+t.name+"] ("+string.Join(",",t.columns.Select(c=>"["+c+"]"))+") VALUES;\n");using var csv=new StreamWriter(archive.CreateEntry("01_BANCO_DE_DADOS_COMPLETO/schema/"+t.name+".csv").Open());csv.WriteLine(string.Join(';',t.columns));}
            using var manifest=new StreamWriter(archive.CreateEntry("01_BANCO_DE_DADOS_COMPLETO/import-manifest.json").Open());manifest.Write(JsonSerializer.Serialize(new{version=1,tables=tables.Select(t=>new{t.name,rows=0})}));}}
    public static void Run()=>RunAsync().GetAwaiter().GetResult();
    static async Task RunAsync()
    {
        var passed=0;void Check(bool b,string label){if(!b)throw new InvalidOperationException(label);passed++;Console.WriteLine("PASS "+label);}
        async Task Reject(Func<Task> a,int code,string label){try{await a();throw new InvalidOperationException("Not rejected: "+label);}catch(RuleException ex){Check(ex.Status==code,label);}}
        var root=Path.GetFullPath(Path.Combine("test-results","commercial-"+Guid.NewGuid().ToString("N")));var env=new Env(Directory.GetCurrentDirectory());var config=new ConfigurationBuilder().AddInMemoryCollection(new Dictionary<string,string?>{{"CFC_DATA_DIR",root},{"CFC_INSTALLATION_MODE","commercial"},{"CFC_SCHOOL_ID","school-test"},{"CFC_SCHOOL_NAME","Escola sintética"}}).Build();
        CommercialInstallation.Prepare(config,env);var store=new Store(config,env);var initial=await store.Read();Check(initial.Students.Count==0&&initial.Lessons.Count==0&&initial.Entries.Count==0,"Instalação vazia sem dados de demonstração");Check(store.IsReal&&store.DatabasePath!.EndsWith("school.sqlite"),"Instalação nova utiliza SQLite");
        var admin=initial.Users.Single();Check(admin.MustChangePassword&&admin.Role=="Administrador","Senha inicial requer troca pelo titular");Check(!Passwords.Verify("cfc2026",admin.PasswordHash),"Senha pública de demonstração não funciona");Check(!Passwords.Verify("anything","bad:encoding!"),"Hash inválido não interrompe autenticação");
        var first=File.ReadAllText(Path.Combine(root,"first-access.json"));CommercialInstallation.Prepare(config,env);Check(first==File.ReadAllText(Path.Combine(root,"first-access.json")),"Reinício mantém a senha inicial e os dados");
        config["CFC_SCHOOL_ID"]="other-school";try{CommercialInstallation.Prepare(config,env);throw new Exception("Wrong volume accepted");}catch(InvalidOperationException){Check(true,"Volume de outra escola é recusado");}config["CFC_SCHOOL_ID"]="school-test";
        var queue=new ImportQueue(store,config,env,NullLogger<ImportQueue>.Instance);await Reject(()=>queue.Create(new(){Role="Gerente"},"test.zip",1),403,"Gerente não cria importação");await Reject(()=>queue.Create(admin,"test.exe",1),400,"Formato de envio inválido recusado");await Reject(()=>queue.Create(admin,"test.zip",ImportQueue.MaxZip+1),400,"Limite de tamanho aplicado");
        var zip=Path.Combine(root,"fixture.zip");CreateFixture(root);
        var bytes=await File.ReadAllBytesAsync(zip);var upload=await queue.Create(admin,"fixture.zip",bytes.Length);Check(upload.Offset==0,"Upload é criado sem ativar dados");await Reject(()=>queue.Create(admin,"second.zip",1),409,"Somente uma importação por vez");await Reject(()=>queue.Append(admin,upload.Id,1,new MemoryStream(bytes),bytes.Length),409,"Offset incorreto não duplica trechos");
        await Reject(()=>queue.Append(admin,upload.Id,0,new MemoryStream(bytes[..^1]),bytes.Length),409,"Envio interrompido não confirma trecho");upload=await queue.Append(admin,upload.Id,0,new MemoryStream(bytes),bytes.Length);Check(upload.Offset==bytes.Length,"Envio pode retomar após trecho interrompido");Check(!File.Exists(Path.Combine(root,"import-report.json")),"Upload não executa o SQL");
        await queue.Enqueue(admin,upload.Id);await queue.StartAsync(CancellationToken.None);ImportUpload? done=null;
        for(var i=0;i<900;i++){await Task.Delay(100);var listing=JsonSerializer.SerializeToElement(queue.List(admin),Database.Compact);done=listing.GetProperty("jobs").EnumerateArray().Select(x=>x.Deserialize<ImportUpload>(Database.Compact)!).First(x=>x.Id==upload.Id);if(done.State is "Pronta" or "Falhou")break;}
        Check(done?.State=="Pronta", "Exportação sintética SQL/CSV conferida em processo separado: "+done?.Message);Check(done!.Rows==0&&done.Tables==86,"Todas as tabelas da fixture preservadas");Check(CommercialInstallation.Empty(store),"Staging não muda base ativa");await Reject(()=>queue.Activate(admin,upload.Id,false),409,"Ativação exige confirmação explícita");
        await store.Mutate(admin.Id,Guid.NewGuid().ToString(),"not-empty",s=>{s.Students.Add(new(){Id="temporary",Name="Aluno sintético"});return new{ok=true};});await Reject(()=>queue.Activate(admin,upload.Id,true),409,"Dados operacionais não são substituídos");
        await store.Mutate(admin.Id,Guid.NewGuid().ToString(),"empty-again",s=>{s.Students.RemoveAll(x=>x.Id=="temporary");return new{ok=true};});await queue.Activate(admin,upload.Id,true);Check(queue.Maintenance,"Ativação inicia modo de manutenção");var reopened=new Store(config,env);var preserved=await reopened.UserById(admin.Id);Check(preserved?.PasswordHash==admin.PasswordHash,"Administrador atual mantém acesso após importação");Check(reopened.DatabasePath!=store.DatabasePath,"Ativação troca manifesto preservando banco anterior");await queue.StopAsync(CancellationToken.None);
        async Task BadZip(string entry,string label){var f=Path.Combine(root,Guid.NewGuid()+".zip");using(var a=ZipFile.Open(f,ZipArchiveMode.Create)){using var w=new StreamWriter(a.CreateEntry(entry).Open());w.Write("test");}try{await ImportQueue.Extract(f,Path.Combine(root,Guid.NewGuid().ToString()),CancellationToken.None);throw new Exception("Accepted "+label);}catch(InvalidDataException){Check(true,label);}}
        await BadZip("01_BANCO_DE_DADOS_COMPLETO/../../outside.sql","ZIP com travessia de diretórios recusado");await BadZip("01_BANCO_DE_DADOS_COMPLETO/program.exe","Executável dentro do pacote recusado");await BadZip("other/only.csv","ZIP sem estrutura conhecida recusado");
        var inv=Path.Combine(root,"inventory");Directory.CreateDirectory(inv);File.WriteAllText(Path.Combine(inv,"import-manifest.json"),"{\"version\":1,\"tables\":[{\"name\":\"bad;name\",\"rows\":0}]}");try{await PackageImporter.Inventory(inv);throw new Exception("Bad manifest accepted");}catch(InvalidDataException){Check(true,"Inventário com nome de tabela inválido recusado");}
        File.WriteAllText(Path.Combine(root,"result.json"),JsonSerializer.Serialize(new{ok=true,checks=passed,fixture="synthetic tables, zero personal records"},Store.Json));Console.WriteLine(passed+" verificações comerciais aprovadas.");
    }
}
