using System.Globalization;
using System.Text.Json;
using Microsoft.Data.Sqlite;
namespace CfcPilot;
public sealed class FinanceSummary
{
 public decimal Debits{get;set;}public decimal ReceivedGross{get;set;}public decimal PaymentRefunds{get;set;}public decimal CreditsGross{get;set;}public decimal CreditReversals{get;set;}public decimal UnknownReversals{get;set;}public decimal Revenues{get;set;}public decimal Expenses{get;set;}public decimal Unclassified{get;set;}
 public decimal Paid=>ReceivedGross-PaymentRefunds;public decimal Credits=>CreditsGross-CreditReversals;public decimal Balance=>Debits-Paid-Credits+UnknownReversals;public decimal Outstanding=>Math.Max(0,Balance);public decimal CreditBalance=>Math.Max(0,-Balance);public decimal CashNet=>Paid+Revenues-Expenses;
 public decimal ScheduledOutstanding{get;set;}public decimal Overdue{get;set;}public decimal DueToday{get;set;}public decimal Upcoming=>Math.Max(0,ScheduledOutstanding-Overdue-DueToday);public decimal ReconciliationDifference=>Balance-ScheduledOutstanding;
}
public sealed class FinanceService(Store store)
{
 const string Cents="CAST(round(CAST(e.amount AS REAL)*100) AS INTEGER)";
 static decimal Amount(Dictionary<string,string?> row,string key)=>decimal.Parse(row.GetValueOrDefault(key)??"0",CultureInfo.InvariantCulture)/100;
 static List<T> Entities<T>(IEnumerable<Dictionary<string,string?>> rows)=>rows.Select(r=>JsonSerializer.Deserialize<T>(r["json"]!,Store.Json)!).ToList();
 public static FinanceSummary Calculate(IEnumerable<Entry> entries,IEnumerable<Installment> parts,string today,IEnumerable<Entry>? reference=null)
 {
 var rows=entries.ToArray();var byId=(reference??rows).ToDictionary(e=>e.Id);var r=new FinanceSummary();foreach(var e in rows){switch(e.Kind){case "Débito":r.Debits+=e.Amount;break;case "Recebimento":r.ReceivedGross+=e.Amount;break;case "Crédito":r.CreditsGross+=e.Amount;break;case "Receita":r.Revenues+=e.Amount;break;case "Despesa":r.Expenses+=e.Amount;break;case "Estorno":var kind=byId.GetValueOrDefault(e.Reverses)?.Kind;if(kind=="Recebimento")r.PaymentRefunds+=e.Amount;else if(kind=="Crédito")r.CreditReversals+=e.Amount;else r.UnknownReversals+=e.Amount;break;default:r.Unclassified+=e.Amount;break;}}
 foreach(var p in parts.Where(p=>p.Status!="Cancelada")){var remaining=Math.Max(0,p.Amount-p.Paid);r.ScheduledOutstanding+=remaining;if(p.Due.CompareTo(today)<0)r.Overdue+=remaining;else if(p.Due==today)r.DueToday+=remaining;}return r;
 }
 FinanceSummary Totals(SqliteConnection db,string unit,string student,string from,string until,bool includeParts)
 {
 var groups=Database.Rows(db,"SELECT json_extract(e.json,'$.kind') AS type,json_extract(o.json,'$.kind') AS original,COALESCE(SUM("+Cents+"),0) AS cents FROM entities e LEFT JOIN entities o ON o.kind='Entries' AND o.id=json_extract(e.json,'$.reverses') WHERE e.kind='Entries' AND ($0='' OR e.unit_id=$0) AND ($1='' OR e.student_id=$1) AND ($2='' OR e.date>=$2) AND ($3='' OR e.date<$3) GROUP BY type,original",unit,student,from,until);var r=new FinanceSummary();foreach(var g in groups){var amount=Amount(g,"cents");switch(g["type"]){case "Débito":r.Debits+=amount;break;case "Recebimento":r.ReceivedGross+=amount;break;case "Crédito":r.CreditsGross+=amount;break;case "Receita":r.Revenues+=amount;break;case "Despesa":r.Expenses+=amount;break;case "Estorno":if(g["original"]=="Recebimento")r.PaymentRefunds+=amount;else if(g["original"]=="Crédito")r.CreditReversals+=amount;else r.UnknownReversals+=amount;break;default:r.Unclassified+=amount;break;}}
 if(includeParts){var x=Database.Rows(db,"SELECT COALESCE(SUM(MAX(0,CAST(round((CAST(amount AS REAL)-CAST(json_extract(json,'$.paid') AS REAL))*100) AS INTEGER))),0) AS pending,COALESCE(SUM(CASE WHEN json_extract(json,'$.due')<$2 THEN MAX(0,CAST(round((CAST(amount AS REAL)-CAST(json_extract(json,'$.paid') AS REAL))*100) AS INTEGER)) ELSE 0 END),0) AS overdue,COALESCE(SUM(CASE WHEN json_extract(json,'$.due')=$2 THEN MAX(0,CAST(round((CAST(amount AS REAL)-CAST(json_extract(json,'$.paid') AS REAL))*100) AS INTEGER)) ELSE 0 END),0) AS today FROM entities WHERE kind='Installments' AND COALESCE(json_extract(json,'$.status'),'')<>'Cancelada' AND ($0='' OR unit_id=$0) AND ($1='' OR student_id=$1)",unit,student,Operations.Today)[0];r.ScheduledOutstanding=Amount(x,"pending");r.Overdue=Amount(x,"overdue");r.DueToday=Amount(x,"today");}return r;
 }
 public async Task<object> Student(string id,int page)
 {
 page=Math.Clamp(page,1,100000);if(store.DatabasePath==null){var s=await store.Read();var es=s.Entries.Where(e=>e.StudentId==id).ToList();var ps=s.Installments.Where(p=>p.StudentId==id).ToList();return new{summary=Calculate(es,ps,Operations.Today),entries=es.OrderByDescending(e=>e.Date).Skip((page-1)*100).Take(100),installments=ps,enrollments=s.Enrollments.Where(e=>e.StudentId==id),total=es.Count,page,pageSize=100};}
 using var db=Database.Open(store.DatabasePath,true);return new{summary=Totals(db,"",id,"","",true),entries=Entities<Entry>(Database.Rows(db,"SELECT json FROM entities WHERE kind='Entries' AND student_id=$0 ORDER BY date DESC,id DESC LIMIT 100 OFFSET $1",id,(page-1)*100)),installments=Entities<Installment>(Database.Rows(db,"SELECT json FROM entities WHERE kind='Installments' AND student_id=$0 ORDER BY json_extract(json,'$.due'),id LIMIT 500",id)),enrollments=Entities<Enrollment>(Database.Rows(db,"SELECT json FROM entities WHERE kind='Enrollments' AND student_id=$0",id)),total=Database.Count(db,"SELECT count(*) FROM entities WHERE kind='Entries' AND student_id=$0",id),installmentTotal=Database.Count(db,"SELECT count(*) FROM entities WHERE kind='Installments' AND student_id=$0",id),page,pageSize=100};
 }
 public async Task<object> General(string unit,string from,string until,int page)
 {
 if(store.DatabasePath==null){var s=await store.Read();var rows=s.Entries.Where(e=>(unit==""||e.UnitId==unit)&&e.Date.CompareTo(from)>=0&&e.Date.CompareTo(until)<0).ToArray();return new{period=Calculate(rows,[],Operations.Today,s.Entries),portfolio=Calculate(s.Entries.Where(e=>unit==""||e.UnitId==unit),s.Installments.Where(e=>unit==""||e.UnitId==unit),Operations.Today),rows=rows.OrderByDescending(e=>e.Date).Skip((page-1)*100).Take(100).Select(e=>new{entry=e,studentName=s.Students.Find(x=>x.Id==e.StudentId)?.Name??"",userName=s.Users.Find(x=>x.Id==e.UserId)?.Name??""}),total=rows.Length,page,pageSize=100,accountOutstanding=s.Entries.Where(e=>e.StudentId!=""&&(unit==""||e.UnitId==unit)).GroupBy(e=>e.StudentId).Sum(g=>Calculate(g,[],Operations.Today,s.Entries).Outstanding),accountCredits=s.Entries.Where(e=>e.StudentId!=""&&(unit==""||e.UnitId==unit)).GroupBy(e=>e.StudentId).Sum(g=>Calculate(g,[],Operations.Today,s.Entries).CreditBalance),receivables=s.Installments.Where(p=>p.Status!="Cancelada"&&p.Amount>p.Paid&&(unit==""||p.UnitId==unit)).GroupBy(p=>p.StudentId).Select(g=>new{student_id=g.Key,name=s.Students.Find(x=>x.Id==g.Key)?.Name??"Aluno sem cadastro vinculado",due=g.Min(p=>p.Due),cents=g.Sum(p=>(p.Amount-p.Paid)*100),installments=g.Count()}).OrderBy(x=>x.due).Take(50)};}
 using var db=Database.Open(store.DatabasePath,true);var ledger=store.Ledger(unit,from,until,page);var json=JsonSerializer.SerializeToElement(ledger,Store.Json);var portfolio=Totals(db,unit,"","","",true);
 // Sum positive balances separately: one student's credit never clears another student's debt.
 var balances=Database.Rows(db,"SELECT COALESCE(SUM(MAX(0,b)),0) AS outstanding,COALESCE(SUM(MAX(0,-b)),0) AS credit FROM (SELECT student_id,SUM(CASE WHEN json_extract(json,'$.kind') IN('Débito','Estorno') THEN CAST(round(CAST(amount AS REAL)*100) AS INTEGER) WHEN json_extract(json,'$.kind') IN('Recebimento','Crédito') THEN -CAST(round(CAST(amount AS REAL)*100) AS INTEGER) ELSE 0 END) AS b FROM entities WHERE kind='Entries' AND student_id<>'' AND ($0='' OR unit_id=$0) GROUP BY student_id)",unit)[0];
 var receivables=Database.Rows(db,"SELECT p.student_id,COALESCE(json_extract(s.json,'$.name'),'Aluno sem cadastro vinculado') AS name,MIN(json_extract(p.json,'$.due')) AS due,SUM(MAX(0,CAST(round((CAST(p.amount AS REAL)-CAST(json_extract(p.json,'$.paid') AS REAL))*100) AS INTEGER))) AS cents,COUNT(*) AS installments FROM entities p LEFT JOIN entities s ON s.kind='Students' AND s.id=p.student_id WHERE p.kind='Installments' AND COALESCE(json_extract(p.json,'$.status'),'')<>'Cancelada' AND CAST(p.amount AS REAL)>CAST(json_extract(p.json,'$.paid') AS REAL) AND ($0='' OR p.unit_id=$0) GROUP BY p.student_id ORDER BY due LIMIT 50",unit);
 return new{period=Totals(db,unit,"",from,until,false),portfolio,accountOutstanding=Amount(balances,"outstanding"),accountCredits=Amount(balances,"credit"),rows=json.GetProperty("rows"),total=json.GetProperty("total"),page,pageSize=100,receivables,receivablesLimitedTo=50};
 }
}
