using System.Text.Json;
namespace CfcPilot;
public static class FinanceChecks
{
 sealed class Env(string root):IWebHostEnvironment{public string ApplicationName{get;set;}="CfcPilot";public string EnvironmentName{get;set;}="Testing";public string ContentRootPath{get;set;}=root;public Microsoft.Extensions.FileProviders.IFileProvider ContentRootFileProvider{get;set;}=new Microsoft.Extensions.FileProviders.NullFileProvider();public string WebRootPath{get;set;}=root;public Microsoft.Extensions.FileProviders.IFileProvider WebRootFileProvider{get;set;}=new Microsoft.Extensions.FileProviders.NullFileProvider();}
 static void Check(bool condition,string label){if(!condition)throw new InvalidOperationException(label);Console.WriteLine("PASS "+label);}
 public static async Task Run()
 {
 var today=Operations.Today;var rows=new List<Entry>{new(){Id="debit",StudentId="one",UnitId="main",Kind="Débito",Amount=1000,Date=today},new(){Id="old-payment",StudentId="one",UnitId="main",Kind="Recebimento",Amount=200,Voided=true,Date="2000-01-01"},new(){Id="refund",StudentId="one",UnitId="main",Kind="Estorno",Amount=200,Reverses="old-payment",Date=today},new(){Id="discount",StudentId="one",UnitId="main",Kind="Crédito",Amount=50,Voided=true,Date="2000-01-01"},new(){Id="discount-reversal",StudentId="one",UnitId="main",Kind="Estorno",Amount=50,Reverses="discount",Date=today},new(){Id="money",StudentId="one",UnitId="main",Kind="Recebimento",Amount=123.45m,Date=today},new(){Id="credit",StudentId="two",UnitId="main",Kind="Crédito",Amount=300,Date=today}};
 var parts=new List<Installment>{new(){Id="part",StudentId="one",UnitId="main",Amount=1000,Paid=123.45m,Due="2000-01-01"},new(){Id="canceled",StudentId="one",UnitId="main",Amount=500,Status="Cancelada",Due="2000-01-01"}};
 var r=FinanceService.Calculate(rows.Where(e=>e.StudentId=="one"),parts,today);Check(r.Paid==123.45m&&r.Credits==0&&r.Outstanding==876.55m,"Originais estornados permanecem e centavos conciliam");Check(r.Overdue==876.55m&&r.ReconciliationDifference==0,"Parcelas canceladas não geram cobrança");var period=FinanceService.Calculate(rows.Where(e=>e.Date==today),[],today,rows);Check(period.PaymentRefunds==200&&period.CreditReversals==50&&period.CashNet==-76.55m,"Estorno de pagamento fora do período e crédito têm classificações distintas");Check(FinanceService.Calculate([new(){Id="unknown",Kind="Estorno",Amount=1,Reverses="missing"}],[],today).UnknownReversals==1,"Estorno sem vínculo é identificado para conferência");
 var root=Path.Combine(Path.GetTempPath(),"cfc-finance-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);try{var dbFile=Path.Combine(root,"test.sqlite");using(var db=Database.Open(dbFile)){Database.Initialize(db);foreach(var e in rows)Database.SaveEntity(db,"Entries",e);foreach(var p in parts)Database.SaveEntity(db,"Installments",p);for(int i=0;i<110;i++)Database.SaveEntity(db,"Entries",new Entry{Id="history-"+i,Kind="Receita",Amount=.01m,Date=today,UnitId="main"});Database.Execute(db,"INSERT INTO metadata VALUES('revision','0')");}CommercialInstallation.Write(Path.Combine(root,"active-database.json"),new{path="test.sqlite",importId="synthetic"});var config=new ConfigurationBuilder().AddInMemoryCollection(new Dictionary<string,string?>{{"CFC_DATA_DIR",root}}).Build();var env=new Env(root);var service=new FinanceService(new Store(config,env));var current=JsonSerializer.SerializeToElement(await service.Student("one",1),Store.Json);Check(current.GetProperty("summary").GetProperty("paid").GetDecimal()==123.45m,"SQL e cálculo em memória concordam");var general=JsonSerializer.SerializeToElement(await service.General("",today,Operations.Now.AddDays(1).ToString("yyyy-MM-dd"),1),Store.Json);Check(general.GetProperty("accountOutstanding").GetDecimal()==876.55m&&general.GetProperty("accountCredits").GetDecimal()==300,"Crédito de um aluno não compensa dívida de outro");Check(general.GetProperty("period").GetProperty("paymentRefunds").GetDecimal()==200&&general.GetProperty("period").GetProperty("creditReversals").GetDecimal()==50,"SQL classifica estornos por original fora do período");Check(general.GetProperty("rows").GetArrayLength()==100&&general.GetProperty("total").GetInt32()>100&&general.GetProperty("period").GetProperty("revenues").GetDecimal()==1.10m,"Paginação não limita os totais financeiros");}finally{Microsoft.Data.Sqlite.SqliteConnection.ClearAllPools();if(!Path.GetFullPath(root).StartsWith(Path.GetFullPath(Path.GetTempPath())+"cfc-finance-",StringComparison.OrdinalIgnoreCase))throw new InvalidOperationException("Diretório de teste fora do destino esperado.");Directory.Delete(root,true);}
 }
}
